# SPDX-FileCopyrightText: The Calyx Institute
# SPDX-License-Identifier: Apache-2.0

include:
  - project: 'CalyxOS/ci-templates'
    file: '/.gerrit-ci-template.yml'

# Keep this image in sync with IMAGE in build.sh
image: golang:1.26.8

variables:
  GOCACHE: /tmp/gocache
  GOPATH: /tmp/gopath
  GIT_DEPTH: 0

stages:
  - test
  - build
  - deploy
  - vote

pre-commit:
  stage: test
  extends: .gerrit_checkout
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends python3-pip
    - pip3 install --break-system-packages --no-cache-dir pre-commit
    - pre-commit run --all-files --show-diff-on-failure

compile:
  stage: build
  extends: .gerrit_checkout
  script:
    - make
  artifacts:
    name: device-flasher
    expire_in: 1 week
    paths:
      - '*.linux'
      - '*.exe'
      - '*.darwin'
      - '*.sha256sum'
