# SPDX-FileCopyrightText: The Calyx Institute
# SPDX-License-Identifier: Apache-2.0

exclude: '^(vendor|src)/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -l -w
        language: system
        types: [go]
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        types: [go]
      - id: staticcheck
        name: staticcheck
        entry: go run honnef.co/go/tools/cmd/staticcheck@v0.8.1 -debug.run-quickfix-analyzers -checks=all ./...
        language: system
        pass_filenames: false
        types: [go]
      - id: modernize
        name: modernize (go fix)
        entry: go run golang.org/x/tools/go/analysis/passes/modernize/cmd/modernize@v0.50.0 ./...
        language: system
        pass_filenames: false
        types: [go]
      - id: go-test
        name: go test
        entry: go test -race ./...
        language: system
        pass_filenames: false
        types: [go]
